### ISSUE TITLE
Optimization for 11 UC Berkley EECS

### ISSUE THREAD

**Issue by caleywoods** [t04glovern/awesome-exapunks#3]
I didn't want to give you any spoilers so I thought I would use this route to check. There's a small code addition (1 line) in `11-uc-berkeley-eecs-department` that I discovered. I assume a lot of people are doing it given the histogram.

I think everyone could implement it into their solutions to save quite a few cycles, in your particular case it takes the cycle count to 157, down from 408.

Let me know if you'd like to see it, I know a lot of the fun in Zach-like games are optimizing / refactoring so I didn't want to blindly throw something out there.

Thanks for sharing this repo! I went back to my original solution and was able to work the cycles down from 800 to 530 and then down to 279 with the line of code I mentioned in the first part of this issue. After I found this repo and read your solution I realized that I completely overlooked being able to count down in my send and receive loops on the two EXA's instead of this stupid back and forth on the M register between the two of them, that let me get my solution down to 180 cycles.

**Comment by t04glovern** [comment]
I bet the optimization is super seeky, err I mean sneaky ;)

Good find though, Its such a small thing that makes a massive difference

**Comment by caleywoods** [comment]
Totally, it's about 126 positions of sneaky. I think it turns the solution "non-pure" if you will but it's fun trying to get the cycles as low as possible.

Now, back to trying to solve TEC Redshift.
